feat: add ExposeIfHasPermissionFor decorator
kittgen/kittgen-nestjs pull request #10
Opened 2021-01-11 21:29 UTC by edgarmueller

2021-01-11 23:57 UTC, ottovw requested changes

2021-01-11 23:57 UTC, ottovw commented on example-apps/my-nest-project/src/app.controller.ts
> +  @UseInterceptors(ExposeIfHasPermissionForInterceptor)
PermissionInterceptor

2021-01-11 23:57 UTC, ottovw commented on example-apps/my-nest-project/src/get-article.dto.ts
> +  @ExposeIfHasPermissionFor('write-article')
ExposeWithPermission

2021-01-11 23:57 UTC, ottovw commented on example-apps/my-nest-project/src/expose-if-has-permission-for.interceptor.ts
> +export class ExposeIfHasPermissionForInterceptor extends ClassSerializerInterceptor {
WTF MATE?! Naming! ;)

2021-01-11 23:58 UTC, edgarmueller commented on example-apps/my-nest-project/src/expose-if-has-permission-for.interceptor.ts
> +export class ExposeIfHasPermissionForInterceptor extends ClassSerializerInterceptor {
🤮

2021-01-13 01:20 UTC, ottovw approved these changes

2021-01-13 01:21 UTC, ottovw commented
@edgarmueller 👍

2021-01-13 08:48 UTC, merged

2021-01-14 17:10 UTC, ottovw commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kittgen/nestjs-authorization/v/1.2.0)
- [GitHub release](https://github.com/kittgen/kittgen-nestjs/releases/tag/nestjs-authorization-v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: