feat: add https middleware package
kittgen/kittgen-nestjs pull request #16
Opened 2021-01-14 21:42 UTC by edgarmueller

2021-01-14 21:58 UTC, ottovw requested changes

2021-01-14 21:58 UTC, ottovw commented on packages/nestjs-https-redirect/.gitignore
> +### https://raw.github.com/github/gitignore/d2c1bb2b9c72ead618c9f6a48280ebc7a8e0dff6/Node.gitignore
.DS_Store is missing

2021-01-14 21:58 UTC, ottovw commented on packages/nestjs-https-redirect/package.json
> +  "dependencies": {
review dependencies

2021-01-14 21:58 UTC, ottovw commented on packages/nestjs-https-redirect/src/https-redirect.middleware.ts
> +    const isHttpProto = req.header('x-forwarded-proto') === 'http';
this is not needed.

2021-01-14 21:58 UTC, ottovw commented on packages/nestjs-https-redirect/src/https-redirect.middleware.ts
> +      const redirectUrl = `https://${req.hostname}${req.originalUrl}`;
are query parameters redirected as well?

2021-01-14 21:58 UTC, ottovw commented on packages/nestjs-https-redirect/README.md
> +
use docu template from authorization

2021-01-14 22:26 UTC, edgarmueller commented on packages/nestjs-https-redirect/src/https-redirect.middleware.ts
> +      const redirectUrl = `https://${req.hostname}${req.originalUrl}`;
AFAIK, yes, see https://expressjs.com/de/api.html `req.originalUrl`

2021-01-14 22:39 UTC, ottovw requested changes

2021-01-14 22:39 UTC, ottovw commented on packages/nestjs-https-redirect/README.md
> +First, make sure enable `trust proxy` for you app:
only if behind reverse proxy (e.g. Heroku or Ngnix)

2021-01-14 22:39 UTC, ottovw commented on packages/nestjs-https-redirect/README.md
> +          .apply(HttpsRedirectMiddleware)
how to pass in configuration?

2021-01-14 22:52 UTC, ottovw commented
insert reference into main README.md

2021-01-14 22:52 UTC, ottovw requested changes

2021-01-14 22:52 UTC, ottovw commented on packages/nestjs-https-redirect/README.md
> +# Kittgen Nestjs HTTPS redirect middleware
add reference to root-level README.md

2021-01-14 23:28 UTC, ottovw approved these changes
👍 💯 🚀

2021-01-14 23:28 UTC, merged

2021-01-17 20:58 UTC, ottovw commented
:tada: This PR is included in version @kittgen/nestjs-authorization-v1.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@kittgen/nestjs-authorization/v/1.4.0)
- [GitHub release](https://github.com/kittgen/kittgen-nestjs/releases/tag/nestjs-authorization-v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: